name: Node.js CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: building...

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: install deps
        run: npm ci
      - name: build static assets
        run: npm run build --if-present
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    name: deploying...

    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]"
        id: extract_branch
      - run: echo "${{ steps.extract_branch.outputs.branch }}"
      - name: "Get branch name and save to env"
        env:
          IS_PR: ${{ github.EVENT_NAME == 'pull_request' }}
        run: |
          if ${IS_PR}; then
            BRANCH_NAME="${GITHUB_HEAD_REF}"
          else
            BRANCH_NAME="${GITHUB_REF##*/}"
          fi
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy ${{ env.BRANCH_NAME }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
