name: Node.js CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: building...

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: install deps
        run: npm ci
      - name: build static assets
        run: npm run build --if-present
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    name: deploying...

    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: example echos...
        run: echo "steps"
      - run: echo ${{ steps }}
      - run: echo "steps.step_id"
      - run: echo ${{ steps.step_id }}
      - run: echo "steps.step_id.outputs"
      - run: echo ${{ steps.step_id.outputs }}
      - run: echo "steps.step_id.outputs.url_output"
      - run: echo ${{ steps.step_id.outputs.url_output }}
      - run: echo "steps.step_id.outcome"
      - run: echo ${{ steps.step_id.outcome }}

      - run: echo "JOBS"
      - run: echo ${{ job }}
      - run: echo "job.container"
      - run: echo ${{ job.container }}
      - run: echo "job.container.id"
      - run: echo ${{ job.container.id }}
      - run: echo "job.container.network"
      - run: echo ${{ job.container.network }}
      - run: echo "job.services"
      - run: echo ${{ job.services }}
      - run: echo "job.status"
      - run: echo ${{ job.status }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy ${{ steps.step_id.outputs.url_output }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
